//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=imsaregistration.database.windows.net;Initial Catalog=ImsaAdminDev;Us" +
            "er ID=HardCardPrinter;Password=TyGe7q6hSPBa")]
        public string ImsaAdminDevConnectionString {
            get {
                return ((string)(this["ImsaAdminDevConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=imsaregistration.database.windows.net;Initial Catalog=ImsaAdminDev;Pe" +
            "rsist Security Info=True;User ID=imsaAdmin;Password=UHEvB2HCazSx")]
        public string ImsaAdminDevConnectionString1 {
            get {
                return ((string)(this["ImsaAdminDevConnectionString1"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("664")]
        public int Selection_Form_Height {
            get {
                return ((int)(this["Selection_Form_Height"]));
            }
            set {
                this["Selection_Form_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("606")]
        public int Selection_Form_Width {
            get {
                return ((int)(this["Selection_Form_Width"]));
            }
            set {
                this["Selection_Form_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("664")]
        public int Next_Selection_Form_Height {
            get {
                return ((int)(this["Next_Selection_Form_Height"]));
            }
            set {
                this["Next_Selection_Form_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("606")]
        public int Next_Selection_Form_Width {
            get {
                return ((int)(this["Next_Selection_Form_Width"]));
            }
            set {
                this["Next_Selection_Form_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("681")]
        public int AC_Photo_Form_Height {
            get {
                return ((int)(this["AC_Photo_Form_Height"]));
            }
            set {
                this["AC_Photo_Form_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("903")]
        public int AC_Photo_Form_Width {
            get {
                return ((int)(this["AC_Photo_Form_Width"]));
            }
            set {
                this["AC_Photo_Form_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("681")]
        public int Next_AC_Photo_Form_Height {
            get {
                return ((int)(this["Next_AC_Photo_Form_Height"]));
            }
            set {
                this["Next_AC_Photo_Form_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("903")]
        public int Next_AC_Photo_Form_Width {
            get {
                return ((int)(this["Next_AC_Photo_Form_Width"]));
            }
            set {
                this["Next_AC_Photo_Form_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("521")]
        public int AC_Timed_Form_Height {
            get {
                return ((int)(this["AC_Timed_Form_Height"]));
            }
            set {
                this["AC_Timed_Form_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("913")]
        public int AC_Timed_Form_Width {
            get {
                return ((int)(this["AC_Timed_Form_Width"]));
            }
            set {
                this["AC_Timed_Form_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("521")]
        public int Next_AC_Timed_Form_Height {
            get {
                return ((int)(this["Next_AC_Timed_Form_Height"]));
            }
            set {
                this["Next_AC_Timed_Form_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("913")]
        public int Next_AC_Timed_Form_Width {
            get {
                return ((int)(this["Next_AC_Timed_Form_Width"]));
            }
            set {
                this["Next_AC_Timed_Form_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("521")]
        public int Member_Form_Height {
            get {
                return ((int)(this["Member_Form_Height"]));
            }
            set {
                this["Member_Form_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("886")]
        public int Member_Form_Width {
            get {
                return ((int)(this["Member_Form_Width"]));
            }
            set {
                this["Member_Form_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("521")]
        public int Next_Member_Form_Height {
            get {
                return ((int)(this["Next_Member_Form_Height"]));
            }
            set {
                this["Next_Member_Form_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("886")]
        public int Next_Member_Form_Width {
            get {
                return ((int)(this["Next_Member_Form_Width"]));
            }
            set {
                this["Next_Member_Form_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("587")]
        public int SEC_Form_Height {
            get {
                return ((int)(this["SEC_Form_Height"]));
            }
            set {
                this["SEC_Form_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("606")]
        public int SEC_Form_Width {
            get {
                return ((int)(this["SEC_Form_Width"]));
            }
            set {
                this["SEC_Form_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("587")]
        public int Next_SEC_Form_Height {
            get {
                return ((int)(this["Next_SEC_Form_Height"]));
            }
            set {
                this["Next_SEC_Form_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("606")]
        public int Next_SEC_Form_Width {
            get {
                return ((int)(this["Next_SEC_Form_Width"]));
            }
            set {
                this["Next_SEC_Form_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("448")]
        public int Notes_Form_Height {
            get {
                return ((int)(this["Notes_Form_Height"]));
            }
            set {
                this["Notes_Form_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("481")]
        public int Notes_Form_Width {
            get {
                return ((int)(this["Notes_Form_Width"]));
            }
            set {
                this["Notes_Form_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("448")]
        public int Next_Notes_Form_Height {
            get {
                return ((int)(this["Next_Notes_Form_Height"]));
            }
            set {
                this["Next_Notes_Form_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("441")]
        public int Next_Notes_Form_Width {
            get {
                return ((int)(this["Next_Notes_Form_Width"]));
            }
            set {
                this["Next_Notes_Form_Width"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=imsaregistration.database.windows.net;Initial Catalog=ImsaAdminDev;Pe" +
            "rsist Security Info=True;User ID=imsaAdmin;Password=UHEvB2HCazSx")]
        public string Connection_String {
            get {
                return ((string)(this["Connection_String"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=imsaregistration.database.windows.net;Initial Catalog=ImsaAdminDev;Pe" +
            "rsist Security Info=True;User ID=imsaAdmin")]
        public string Conn_String {
            get {
                return ((string)(this["Conn_String"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1, 270, 220, 17")]
        public global::System.Drawing.Rectangle SEC_Name_rect {
            get {
                return ((global::System.Drawing.Rectangle)(this["SEC_Name_rect"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2020")]
        public string Season {
            get {
                return ((string)(this["Season"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10, 216, 197, 17")]
        public global::System.Drawing.Rectangle AC_License_Type_rect1 {
            get {
                return ((global::System.Drawing.Rectangle)(this["AC_License_Type_rect1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10, 242, 197, 17")]
        public global::System.Drawing.Rectangle AC_Name_rect2 {
            get {
                return ((global::System.Drawing.Rectangle)(this["AC_Name_rect2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10, 260, 197, 17")]
        public global::System.Drawing.Rectangle AC_Association_rect3 {
            get {
                return ((global::System.Drawing.Rectangle)(this["AC_Association_rect3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10, 309, 197, 17")]
        public global::System.Drawing.Rectangle AC_Member_Number_rect4 {
            get {
                return ((global::System.Drawing.Rectangle)(this["AC_Member_Number_rect4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-325, 122, 315, 17")]
        public global::System.Drawing.Rectangle Member_License_Type_rect1 {
            get {
                return ((global::System.Drawing.Rectangle)(this["Member_License_Type_rect1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-325, 110, 315, 17")]
        public global::System.Drawing.Rectangle Member_Name_rect2 {
            get {
                return ((global::System.Drawing.Rectangle)(this["Member_Name_rect2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-325, 140, 315, 17")]
        public global::System.Drawing.Rectangle Member_Member_Number_rect4 {
            get {
                return ((global::System.Drawing.Rectangle)(this["Member_Member_Number_rect4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("62, 73, 103, 120")]
        public global::System.Drawing.Rectangle AC_PictureBox_Placement {
            get {
                return ((global::System.Drawing.Rectangle)(this["AC_PictureBox_Placement"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("26, 278, 165, 20")]
        public global::System.Drawing.Rectangle AC_Barcode_Placement {
            get {
                return ((global::System.Drawing.Rectangle)(this["AC_Barcode_Placement"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2, 2")]
        public global::System.Drawing.Point Selection_Form_Location {
            get {
                return ((global::System.Drawing.Point)(this["Selection_Form_Location"]));
            }
            set {
                this["Selection_Form_Location"] = value;
            }
        }
    }
}
